name: dvote
description: Decentralized, end-to-end verifiable governance platform client library for Dart.
version: 0.19.1
homepage: https://github.com/vocdoni/dvote-dart
repository: https://github.com/vocdoni/dvote-dart.git
documentation: https://docs.vocdoni.io

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  protobuf: ^1.0.1
  web3dart: ^2.0.0-dev.7
  convert: ^2.1.1
  dvote_crypto: ^0.10.2
  fixnum: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # mockito: ^4.0.0
  # coverage: ^0.13.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
